###############################################################################
# [ WARNING ]
# Configuration file maintained by Juju
# local changes may be overwritten.
###############################################################################
{% if options.keystone_ldap_password_is_vault -%}
[key_manager]
backend = vault

[vault]
vault_url = {{ options.vault_kv.get('vault_url', '') }}
kv_mountpoint = {{ options.vault_kv.get('secret_backend', '') }}
kv_version = 1
{% endif -%}