###############################################################################
# [ WARNING ]
# Configuration file maintained by Juju
# local changes may be overwritten.
###############################################################################
{% if options.keystone_ldap_password_is_vault -%}
[Service]
Environment="OS_VAULT__APPROLE_ROLE_ID={{ options.vault_kv.get('role_id', '') }}"
Environment="OS_VAULT__APPROLE_SECRET_ID={{ options.vault_kv.get('secret_id', '') }}"
{% endif %}
