###############################################################################
# [ WARNING ]
# Configuration file maintained by Juju
# local changes may be overwritten.
###############################################################################
{% if options.keystone_ldap_password_is_vault -%}
[ldap]
password = {{ options.ldap_password.replace('vault://', '') }}
{% endif -%}